import type { Theme } from '@/types/theme.types';

/**
 * Beautiful Chat Bubble Themes
 * Chỉ áp dụng cho chat bubbles, không ảnh hưởng UI chung
 */
export const PREDEFINED_THEMES: Theme[] = [
  {
    id: 'default',
    name: 'Mặc định',
    description: 'Theme mặc định của ứng dụng',
    colors: {
      bubbleOwn: '#0084ff',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #0084ff 0%, #0066cc 100%)',
      bubbleOther: '#f0f0f0',
      bubbleOtherText: '#050505',
      chatBackground: '#ffffff',
      // UI Elements
      iconPrimary: '#0084ff',
      iconSecondary: '#65676b',
      iconHover: '#0066cc',
      buttonBackground: '#0084ff',
      buttonText: '#ffffff',
      inputBackground: '#f0f2f5',
      inputBorder: '#e4e6eb',
      headerBackground: '#ffffff',
      headerText: '#050505',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #0084ff 0%, #0066cc 100%)',
    },
  },
  {
    id: 'superhero',
    name: 'Siêu nhân',
    description: 'Theme năng động như siêu anh hùng',
    colors: {
      bubbleOwn: '#ff4757',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #ff4757 0%, #ff6348 100%)',
      bubbleOther: '#ffe5e5',
      bubbleOtherText: '#2d0000',
      chatBackground: '#fff5f5',
      chatBackgroundGradient: 'linear-gradient(180deg, #fff5f5 0%, #ffe5e5 100%)',
      // UI Elements
      iconPrimary: '#ff4757',
      iconSecondary: '#ff6348',
      iconHover: '#ff3838',
      buttonBackground: '#ff4757',
      buttonText: '#ffffff',
      inputBackground: '#ffe5e5',
      inputBorder: '#ffcccc',
      headerBackground: '#fff5f5',
      headerText: '#2d0000',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #ff4757 0%, #ff6348 100%)',
    },
  },
  {
    id: 'summer',
    name: 'The Summer I Turned Pretty',
    description: 'Mùa 3',
    colors: {
      bubbleOwn: '#00d2ff',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #00d2ff 0%, #3a7bd5 100%)',
      bubbleOther: '#e0f7ff',
      bubbleOtherText: '#003d5c',
      chatBackground: '#f0fbff',
      chatBackgroundGradient: 'linear-gradient(180deg, #e0f7ff 0%, #b3e5fc 100%)',
      // UI Elements
      iconPrimary: '#00d2ff',
      iconSecondary: '#3a7bd5',
      iconHover: '#00b8e6',
      buttonBackground: '#00d2ff',
      buttonText: '#ffffff',
      inputBackground: '#e0f7ff',
      inputBorder: '#b3e5fc',
      headerBackground: '#f0fbff',
      headerText: '#003d5c',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #00d2ff 0%, #3a7bd5 100%)',
    },
    backgroundImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop',
  },
  {
    id: 'relax',
    name: 'Thư giãn',
    colors: {
      bubbleOwn: '#4a90e2',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      bubbleOther: '#e8eef7',
      bubbleOtherText: '#1a1a2e',
      chatBackground: '#f5f7fb',
      chatBackgroundGradient: 'linear-gradient(180deg, #e8eef7 0%, #d4dff5 100%)',
      // UI Elements
      iconPrimary: '#667eea',
      iconSecondary: '#764ba2',
      iconHover: '#5568d3',
      buttonBackground: '#667eea',
      buttonText: '#ffffff',
      inputBackground: '#e8eef7',
      inputBorder: '#d4dff5',
      headerBackground: '#f5f7fb',
      headerText: '#1a1a2e',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    },
  },
  {
    id: 'heart-drive',
    name: 'Heart Drive',
    description: 'Tác phẩm của Digital Joy',
    colors: {
      bubbleOwn: '#ff6b9d',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #ff6b9d 0%, #c44569 100%)',
      bubbleOther: '#ffe3f0',
      bubbleOtherText: '#5a002e',
      chatBackground: '#fff5f9',
      chatBackgroundGradient: 'linear-gradient(180deg, #ffe3f0 0%, #ffc2d9 100%)',
      // UI Elements
      iconPrimary: '#ff6b9d',
      iconSecondary: '#c44569',
      iconHover: '#ff5588',
      buttonBackground: '#ff6b9d',
      buttonText: '#ffffff',
      inputBackground: '#ffe3f0',
      inputBorder: '#ffc2d9',
      headerBackground: '#fff5f9',
      headerText: '#5a002e',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #ff6b9d 0%, #c44569 100%)',
    },
    backgroundImage: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400&h=300&fit=crop',
  },
  {
    id: 'autumn',
    name: 'Xúc cảm mùa hè',
    description: 'Tác phẩm của Thomas Burden',
    colors: {
      bubbleOwn: '#ff9966',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)',
      bubbleOther: '#fff0e6',
      bubbleOtherText: '#5c2900',
      chatBackground: '#fff8f3',
      chatBackgroundGradient: 'linear-gradient(180deg, #fff0e6 0%, #ffe6cc 100%)',
      // UI Elements
      iconPrimary: '#ff9966',
      iconSecondary: '#ff5e62',
      iconHover: '#ff8855',
      buttonBackground: '#ff9966',
      buttonText: '#ffffff',
      inputBackground: '#fff0e6',
      inputBorder: '#ffe6cc',
      headerBackground: '#fff8f3',
      headerText: '#5c2900',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)',
    },
    backgroundImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
  },
  {
    id: 'karol-g',
    name: 'Karol G',
    description: 'Tropicoqueta',
    colors: {
      bubbleOwn: '#d946ef',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #d946ef 0%, #ec4899 100%)',
      bubbleOther: '#fae8ff',
      bubbleOtherText: '#3d0066',
      chatBackground: '#fdf4ff',
      chatBackgroundGradient: 'linear-gradient(180deg, #fae8ff 0%, #f5d0fe 100%)',
      // UI Elements
      iconPrimary: '#d946ef',
      iconSecondary: '#ec4899',
      iconHover: '#c730e0',
      buttonBackground: '#d946ef',
      buttonText: '#ffffff',
      inputBackground: '#fae8ff',
      inputBorder: '#f5d0fe',
      headerBackground: '#fdf4ff',
      headerText: '#3d0066',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #d946ef 0%, #ec4899 100%)',
    },
  },
  {
    id: 'shape-friends',
    name: 'Shape Friends',
    colors: {
      bubbleOwn: '#20bf6b',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #20bf6b 0%, #01a3a4 100%)',
      bubbleOther: '#e8f8f1',
      bubbleOtherText: '#004d1a',
      chatBackground: '#f2fbf7',
      chatBackgroundGradient: 'linear-gradient(180deg, #e8f8f1 0%, #d1f2e4 100%)',
      // UI Elements
      iconPrimary: '#20bf6b',
      iconSecondary: '#01a3a4',
      iconHover: '#1aa85d',
      buttonBackground: '#20bf6b',
      buttonText: '#ffffff',
      inputBackground: '#e8f8f1',
      inputBorder: '#d1f2e4',
      headerBackground: '#f2fbf7',
      headerText: '#004d1a',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #20bf6b 0%, #01a3a4 100%)',
    },
  },
  {
    id: 'avatar',
    name: 'Avatar: Lửa Và Trò Tận',
    colors: {
      bubbleOwn: '#fc5c65',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #fc5c65 0%, #fd9644 100%)',
      bubbleOther: '#ffe8e8',
      bubbleOtherText: '#4d0000',
      chatBackground: '#fff5f5',
      chatBackgroundGradient: 'linear-gradient(180deg, #ffe8e8 0%, #ffd1d1 100%)',
      // UI Elements
      iconPrimary: '#fc5c65',
      iconSecondary: '#fd9644',
      iconHover: '#eb4c55',
      buttonBackground: '#fc5c65',
      buttonText: '#ffffff',
      inputBackground: '#ffe8e8',
      inputBorder: '#ffd1d1',
      headerBackground: '#fff5f5',
      headerText: '#4d0000',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #fc5c65 0%, #fd9644 100%)',
    },
    backgroundImage: 'https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=400&h=300&fit=crop',
  },
  {
    id: 'wicked',
    name: 'Wicked: For Good',
    colors: {
      bubbleOwn: '#26de81',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #26de81 0%, #20bf6b 100%)',
      bubbleOther: '#e5f9f0',
      bubbleOtherText: '#003d1a',
      chatBackground: '#f0fdf6',
      chatBackgroundGradient: 'linear-gradient(180deg, #e5f9f0 0%, #ccf2df 100%)',
      // UI Elements
      iconPrimary: '#26de81',
      iconSecondary: '#20bf6b',
      iconHover: '#1fc971',
      buttonBackground: '#26de81',
      buttonText: '#ffffff',
      inputBackground: '#e5f9f0',
      inputBorder: '#ccf2df',
      headerBackground: '#f0fdf6',
      headerText: '#003d1a',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #26de81 0%, #20bf6b 100%)',
    },
  },
  {
    id: 'kpop',
    name: 'Thợ săn quý KPop',
    colors: {
      bubbleOwn: '#a29bfe',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)',
      bubbleOther: '#f0eeff',
      bubbleOtherText: '#1a0066',
      chatBackground: '#f7f5ff',
      chatBackgroundGradient: 'linear-gradient(180deg, #f0eeff 0%, #e0d9ff 100%)',
      // UI Elements
      iconPrimary: '#a29bfe',
      iconSecondary: '#6c5ce7',
      iconHover: '#9189f5',
      buttonBackground: '#a29bfe',
      buttonText: '#ffffff',
      inputBackground: '#f0eeff',
      inputBorder: '#e0d9ff',
      headerBackground: '#f7f5ff',
      headerText: '#1a0066',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)',
    },
  },
  {
    id: 'hello-2026',
    name: 'Hello 2026!',
    colors: {
      bubbleOwn: '#fed330',
      bubbleOwnText: '#2d3436',
      bubbleOwnGradient: 'linear-gradient(135deg, #fed330 0%, #f7b731 100%)',
      bubbleOther: '#fffbea',
      bubbleOtherText: '#4d3800',
      chatBackground: '#fffef5',
      chatBackgroundGradient: 'linear-gradient(180deg, #fffbea 0%, #fff6d1 100%)',
      // UI Elements
      iconPrimary: '#f7b731',
      iconSecondary: '#fed330',
      iconHover: '#e6a520',
      buttonBackground: '#fed330',
      buttonText: '#2d3436',
      inputBackground: '#fffbea',
      inputBorder: '#fff6d1',
      headerBackground: '#fffef5',
      headerText: '#4d3800',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #fed330 0%, #f7b731 100%)',
    },
  },
  {
    id: 'the-cool-crew',
    name: 'The Cool Crew',
    description: 'Tác phẩm của Thomas Burden',
    colors: {
      bubbleOwn: '#45aaf2',
      bubbleOwnText: '#ffffff',
      bubbleOwnGradient: 'linear-gradient(135deg, #45aaf2 0%, #2d98da 100%)',
      bubbleOther: '#e8f4fd',
      bubbleOtherText: '#00305a',
      chatBackground: '#f5faff',
      chatBackgroundGradient: 'linear-gradient(180deg, #e8f4fd 0%, #d1e9fa 100%)',
      // UI Elements
      iconPrimary: '#45aaf2',
      iconSecondary: '#2d98da',
      iconHover: '#3498e3',
      buttonBackground: '#45aaf2',
      buttonText: '#ffffff',
      inputBackground: '#e8f4fd',
      inputBorder: '#d1e9fa',
      headerBackground: '#f5faff',
      headerText: '#00305a',
    },
    pattern: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #45aaf2 0%, #2d98da 100%)',
    },
    backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
  },
];

export const DEFAULT_THEME_ID = 'default';

export const getThemeById = (themeId: string): Theme | undefined => {
  return PREDEFINED_THEMES.find(theme => theme.id === themeId);
};

export const getDefaultTheme = (): Theme => {
  return PREDEFINED_THEMES.find(theme => theme.id === DEFAULT_THEME_ID) || PREDEFINED_THEMES[0];
};
